version: "3.9"

services:
  postgres:
    image: postgres:latest
#    ports:
#      - "5432:5432" #only for test
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}

  servicebusdocker:
    image: servicebusdocker:latest
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres